#--------------------------------------------------
# FIRST BUILD THE FLASK APP THAN START THE APP
#---------------------------------------------------
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      TZ: Europe/Belgrade
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      APP_ADMIN_USER: ${APP_ADMIN_USER}
      APP_ADMIN_PASS: ${APP_ADMIN_PASS}
      SECRET_KEY:  ${SECRET_KEY}
      CRON_JOB_SECRET: ${CRON_JOB_SECRET}
      MAIL_PASSWORD:  ${MAIL_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      TZ: Europe/Belgrade
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      TZ: Europe/Belgrade
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
