#--------------------------------------------------
# START ALREADY BUILD DOCKER IMAGES
#---------------------------------------------------
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: Europe/Belgrade
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      #WAIT UNTIL POSTGRES IS READY THAN START FLASK OR PGADMIN
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  flask:
    image: cpe-analiza-flask:latest
    ports:
      - "5000:5000"
    environment:
      TZ: Europe/Belgrade
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      APP_ADMIN_USER: ${APP_ADMIN_USER}
      APP_ADMIN_PASS: ${APP_ADMIN_PASS}
      SECRET_KEY: ${SECRET_KEY}
      CRON_JOB_SECRET: ${CRON_JOB_SECRET}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    environment:
      TZ: Europe/Belgrade
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS}
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
